### ISSUE TITLE
과제 1 피드백

### ISSUE THREAD

**Issue by Dokkabei97** [Gans2/Java_tut#1]
```java
System.out.println("이름을 입력하십쇼");        
name = sc.next();
```
다음 코드를 사용시 

영어권에 사는 'Tom Clancy'가 이름을 입력하면

'Tom'만 출력이 된다고 한다 그렇다면 코드를 어떻게 수정해야 하는가

**Comment by Gans2** [comment]
영어권이니까 퍼스트 네임 적지말고 네임만 적으라고 해
