### ISSUE TITLE
과제2 피드백

### ISSUE THREAD

**Issue by Dokkabei97** [Gans2/Java_tut#2]
```java

if (user == 0) {
    System.out.println("Player : 가위");
} else if (user == 1) {
     System.out.println("Player : 바위");
} else if (user == 2) {
     System.out.println("Player : 보");
} else {
     System.out.println("값을 잘못 입력하셨습니다.");
     System.out.println("게임을 다시 시작해 주십시오.");
     break;
}
```
값을 잘못 입력시
break; 주고 게임을 다시 시작하기보단
continue;를 이용해서 제대로 된 값 입력할때 까지 반복하는게 더 좋음

그리고 특정 값 입력시 그때 break 걸어서 종료하면 더 깔금 ex)9를 입력시 게임 종료

위 말고도 각 조건문에 else if(user > 2) break; 한 이유?

**Comment by Gans2** [comment]
피드백 부분 수정 완료
위 말고도 각 조건문에 else if(user > 2) break; 한 이유? >  처음 적었던 조건문을 복붙해서 쓰다보니 그런 것...

**Comment by Dokkabei97** [comment]
가위가 0 인데 종료도 0으로 해서 슈뢰딩거의 가위바위보를 만들면 어쩌노
